### ISSUE TITLE
Plan controller predict default PV action.

### ISSUE THREAD

**Issue by jortel** [fusor/mig-controller#147]
The controller can predict a good default for PV actions.  The user would still review and make the final selection before running migrations.  This just save the user a lot of clicks/typing.  The default for _local_ storage would be `copy` and for _mounted_ storage it would be `move`.

**Comment by jwmatthews** [comment]
When we look to see if storage is remote, will we also perform a validation to ensure the remote storage is accessible on the destination cluster?

I have some concerns about migrations between data centers/clouds where storage is remote but not accessible on the destination side.  

I suggest we hold on implementing this, let's keep the default as 'copy' and revisit this for a future enhancement when we know more about user usage to see if this helps.

I feel like making the 'move' be explicit is good for now since 'move' has potential to touch the data and break something when the app spins up on destination side.   Copy is safer as it has minimal impact to source side so should be easy to recover if anything goes wrong on destination with migration.

**Comment by jortel** [comment]
> I suggest we hold on implementing this, let's keep the default as 'copy' and revisit this for a future enhancement when we know more about user usage to see if this helps.
> 
> I feel like making the 'move' be explicit is good for now since 'move' has potential to touch the data and break something when the app spins up on destination side. Copy is safer as it has minimal impact to source side so should be easy to recover if anything goes wrong on destination with migration.

Agreed that copy is safer.
But, given that most users are using remote storage and seems likely they'll want to `move`, default to `copy` does not add any real value.  It won't reduce the number of user clicks in the UI or edits using the CLI/API.
