### ISSUE TITLE
Restic PV restore does not work when pod to be restored is `Unschedulable` on destination cluster

### ISSUE THREAD

**Issue by pranavgaikwad** [fusor/mig-controller#177]
This is related to #151 

I have an OCP v3.11.104 and OCP v4.1.0 environments deployed with agnosticd. I am trying to migrate an MsSQL server app (with a NFS PV) deployed on OCP 3. I have the controller deployed on v4 side. 

**Problem**
The backup stage completes without errors. However, the restic restore on the destination is not working. The pod gets restored, but is stuck in pending state. The migration is stuck at `CreateStagePodsStarted` phase. The Velero restore is in `InProgress` phase.

**Identified Cause**

Whenever a pod to be restored has a PV associated (`copy` action in our case), Velero adds an init container to that pod at the time of restore. Velero then restores the pod. The init container waits until the Restic restore process is completed. On the other hand, the restic process does not start until the init container is started. In an ideal scenario, as soon as the pod is restored, the init container runs and triggers the restic restore process. The restic restore process finishes and init container exits. Then, the pod comes live with the PV attached to it. 

In my case, the pod which got backed up, had a nodeSelector looking for label `node-role.kubernetes.io/compute:"true"`. This label is not present on any of the OCP4 nodes in my setup. At the time of restore, the pod got restored with the nodeSelector. Since the labels were absent, the pod never got scheduled. Since it never got scheduled, the init container never started. Since the init container never started, the Restic process never started. And migration is stuck hoping that the restore will finish. 

**Possible Solution**
Migration plugin could replace the old OCP3 `compute` labels with new OCP4 `worker` labels. 

**Fix**
Fixes need to be done in the plugin. Follow this issue - https://github.com/fusor/ocp-velero-plugin/issues/61

**Comment by pranavgaikwad** [comment]
There is one more issue I am facing which is related to this one. 

As described in this issue, I was stuck with the pod which was not getting scheduled due to missing labels. So, I added expected label to one of the worker nodes. However, the pod still did not get scheduled because the pod was waiting for the PVC to be bound. The PVC had a label selector on the source cluster which got copied over to the destination. However, dynamically provisioned PVCs should not have a label selector. If they have one, the PV will never get created.

**Comment by djwhatle** [comment]
Another issue: if you're trying to work through a PV copy from OpenShift 3->4 where data is copied from `NFS -> EBS (gp2)`, we will need to skip specification of `storageClassName` on the PVC we create (or perhaps set it to nil) so that the default storageClassName will be assumed on the OCP 4 cluster. 

The current behavior of setting `storageClassName: ""` (empty string) will work for binding to NFS PVs (or other non-dynamic, pre-provisioned PVs), but will not trigger the EBS dynamic provisioner.

Soon we will be at the point where we'll have information from the user on which storageClass we should be setting on destination PVCs, allowing users to select their preferred dynamic provisioner.

**Comment by djwhatle** [comment]
**Planned actions to fix the issues above in the short-term to get `copy` workflow running**
1. For *copy workflows*, where we want dynamic provisioning to occur, strip the label selectors from PVCs. Implement via Velero plugin.

1. For *copy + move workflows*,  strip the nodeSelectors from all application Pods so that we don't end up with unschedulable workloads if the available node labels don't match up between cluster versions. Down the road, provide user choice and/or smart conversion among nodeSelectors. Implement via Velero plugin.

1. For *copy workflows*, if we want the default dynamic provisioner to be used (which I think we do for now by default), unset `storageClassName` on PVCs (not sure if this is the same as setting to `nil`, needs investigation). Implement via Velero plugin.

**Comment by sseago** [comment]
So based on recent discussions here, it does sound like 1) and 2) above should go into the plugin. This means they'll be needed in ocp-velero-plugin (since that one hasn't yet been abandoned) and it will also need to be added to openshift-migration-plugin once it's confirmed working in ocp-velero-plugin.

**Comment by pranavgaikwad** [comment]
fixed with https://github.com/fusor/ocp-velero-plugin/pull/62
