### ISSUE TITLE
Cleaning up after completed plans causes them to appear as though they failed

### ISSUE THREAD

**Issue by jmontleon** [fusor/mig-controller#193]
Cleaning up the source cluster after a successfully completed Migration Plan causes it to appear as though it has failed in the UI because the plan becomes Critical.

```
  Conditions:
    Category:              Critical
    Last Transition Time:  2019-07-11T13:37:25Z
    Message:               Namespaces [nfs-test] not found on the source cluster.
    Reason:                NotFound
    Status:                True
    Type:                  NamespaceNotFoundOnSourceCluster
Events:                    <none>
```

**Comment by jortel** [comment]
Closing the plan will prevent this.

**Comment by sseago** [comment]
Well a Closed plan *also* creates a "Critical" condition, since it's the only condition that causes an early exit from Reconcile, which is the behavior we want. If the UI and docs can reflect this properly, we're fine. If the "Critical" name bothers people, we could always create a new Condition category that acts like a Critical condition but doesn't look like an Error/Exception situation, but that would make the reconcile/validation logic more complicated since it would be yet another condition category to check for, etc.

**Comment by jortel** [comment]
The _Closed_ condition could be moved to the _Advisory_ category without much work.

**Comment by jortel** [comment]
Fixed fixed by: https://github.com/fusor/mig-controller/pull/251.
