### ISSUE TITLE
Error during stage pod creation with "Pod update forbidden"

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/mig-controller#266]
During `mssql` migration, which was created by the mig-agnosticd repo, encountered such error message in logs:

```
{"level":"error","ts":1565892880.1345618,"logger":"migration|btqjp","msg":"","error":"Pod \"mssql-deployment-1-7wdzh\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
```

Here is the full log from the migration. The migration finished with success. The error seems to appear during annotation change.

[Logs](https://github.com/fusor/mig-controller/files/3506831/Untitled.txt)

**Comment by dymurray** [comment]
Something with `ensureStagePodsCreated` is failing when it tries to update the application pod to remove the restic annotations. I don't see anything immediately obvious as to why this is a forbidden action since we are only updating the annotations/labels so need to dig in to what exactly is going on here.

**Comment by dymurray** [comment]
Closing for now, if this is hit again we will reopen and address it.
