### ISSUE TITLE
Need to allow usage of https:// with minio (or other providers)

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#270]
See: https://github.com/fusor/mig-ui/issues/454

Need a way to specify CA 
Would also like to expose a means of setting this as 'insecure'

**Comment by dymurray** [comment]
At a minimum, let's allow a user to specify an `https` route and use `insecure` when validating the connection.

**Comment by djwhatle** [comment]
Re-opening this, I think it's feasible to expose a means of setting 'insecure' by choice outlined here: https://github.com/fusor/mig-controller/pull/354#issuecomment-552528652

**Comment by mansam** [comment]
This is a summary of where I'm at in my quest to properly support self-signed certificates and insecure SSL connections for S3-compatible services. There's a lot of moving parts here that all need to know about the certificate or the insecure flag, and I've figured out a way address most but not all of those issues. Restic remains a problem, because it doesn't support insecure SSL connections. It also needs to have the certificate provided to it as a file on the disk which has its path passed to the `restic` command as a parameter, or else it needs the certificate installed in the pod's certificate store.

* mig-controller
  - ✔️ Update s3test function to use s3 cert/insecure 
  - ✔️ Include s3 cert/insecure flag in BSL so it's passed to Velero
* Registry pod
  - ✔️ Include the s3 cert in the cloud secret in order to smuggle the cert onto the registry pod (UpdateRegistrySecret)
  - ✔️ Mount the cert from the secret as a subpath so it's available in the pod's certificate store
  - ✔️ Pass insecure flag to registry via `REGISTRY_STORAGE_S3_SKIPVERIFY` env variable (UpdateRegistryDC)
* Velero pods
  - ✔️ Update s3 session creation code to pass the s3 cert/connect insecurely in velero itself
  - ✔️ Have velero write the s3 cert to disk so that when it shells out to restic it can pass the cert as a parameter (restic --cacert)
  - ❌Can't pass 'insecure' flag to restic
* Restic pods
  - ❌ Restic doesn't support insecure ssl connections at all
  - ❌ I'm not yet sure how to provide the s3 cert to the restic pods

**Comment by dymurray** [comment]
This is fixed, closing.
